<table align="left" width=100%>
    <tr>
        <td width="20%">
            <img src="GL-2.png">
        </td>
        <td>
            <div align="center">
                <font color="#21618C" size=8px>
                  <b> Inclass - Lab <br> (Day 1) </b>
                </font>
            </div>
        </td>
    </tr>
</table>

##  Table of Content

1. **[One Dimensional Array](#1D)**
2. **[Two Dimensional Array](#2D)**
3. **[Stacking](#Stacking)**
4. **[Splitting](#Splitting)**
5. **[For Loop](#For Loop)**

**Import the NumPy library before solving the exercises**

### Let's begin with some hands-on practice exercises

<a id="1D"> </a>
## 1. One Dimensional Array

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>1. Write a NumPy program to convert a list of numeric values into a one-dimensional NumPy array</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the list given below: (or create your own list)**<br>

    list_temperature = [3.04, 1.65, 5.76, 1.66, 1.54, 4.69, 2.68]

In [1]:
# type your code here
import numpy as np

# Given list of numeric values
list_temperature = [3.04, 1.65, 5.76, 1.66, 1.54, 4.69, 2.68]

# Convert the list to a one-dimensional NumPy array
temperature_array = np.array(list_temperature)

# Print the resulting NumPy array
print(temperature_array)


[3.04 1.65 5.76 1.66 1.54 4.69 2.68]


<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>2. Create a 1D array of weights of 10 students and retrieve all the weights greater than 68</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the weights given below: (or create your own list)**

    weights = [74.2, 85, 74, 67.9, 52, 70.5, 86, 51.8, 64, 82]

In [2]:
# type your code here
import numpy as np

# Given list of weights
weights = [74.2, 85, 74, 67.9, 52, 70.5, 86, 51.8, 64, 82]

# Create a one-dimensional NumPy array
weights_array = np.array(weights)

# Retrieve all weights greater than 68
weights_greater_than_68 = weights_array[weights_array > 68]

# Print the resulting array
print(weights_greater_than_68)


[74.2 85.  74.  70.5 86.  82. ]


<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>3. Write a code to generate 10 random integers between 20 to 40 (Is it possible to generate same random numbers everytime? If yes, describe the function)
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

In [3]:
# type your code here
import numpy as np

# Set the random seed for reproducibility
np.random.seed(42)

# Generate 10 random integers between 20 and 40 (exclusive of 40)
random_integers = np.random.randint(20, 40, size=10)

# Print the resulting array of random integers
print(random_integers)


[26 39 34 30 27 26 38 30 30 23]


<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>4. Write a program to get the fifth power of the first five positive integers
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

In [4]:
# type your code here
import numpy as np

# Create an array of the first five positive integers
first_five_integers = np.array([1, 2, 3, 4, 5])

# Calculate the fifth power of these integers
fifth_power = first_five_integers ** 5

# Print the resulting array
print(fifth_power)


[   1   32  243 1024 3125]


<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>5. Write a program to create an array of all the odd integers from 50 to 100 
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

In [5]:
# type your code here
import numpy as np

# Create an array of integers from 50 to 100
numbers = np.arange(50, 101)

# Filter to get only odd integers
odd_integers = numbers[numbers % 2 != 0]

# Print the resulting array of odd integers
print(odd_integers)


[51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95 97
 99]


<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>6. Write a program to calculate the sum of each column </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the array given below: (or create your own array)**

    A = [[1, 4, 8], [5, 7, 3], [9, 14, 2]]

In [6]:
# type your code here
import numpy as np

# Given 2D array
A = [[1, 4, 8], [5, 7, 3], [9, 14, 2]]

# Convert the list to a NumPy array
A_array = np.array(A)

# Calculate the sum of each column
column_sums = np.sum(A_array, axis=0)

# Print the resulting sums
print(column_sums)


[15 25 13]


<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>7. Write a code to get the element-wise remainder of an array after division by 8 
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the list given below:**<br>
    
    num = [42, 87, 90, 14, 32, 75, 61, 80, 92]

In [7]:
# type your code here
import numpy as np

# Given list of numbers
num = [42, 87, 90, 14, 32, 75, 61, 80, 92]

# Convert the list to a NumPy array
num_array = np.array(num)

# Get the element-wise remainder after division by 8
remainders = num_array % 8

# Print the resulting remainders
print(remainders)


[2 7 2 6 0 3 5 0 4]


<a id="2D"> </a>
## 2. Two Dimensional Array

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>8. Create a 2D numpy array from a 1D array of 20 elements of your choice. Further, subset the first 5 elements from the second element of a resulting 2D array 
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

In [8]:
# type your code here
import numpy as np

# Create a 1D array of 20 elements
one_d_array = np.arange(1, 21)  # You can choose any 20 elements; here, I'm using 1 to 20

# Reshape the 1D array into a 2D array (for example, 4 rows and 5 columns)
two_d_array = one_d_array.reshape(4, 5)

# Print the resulting 2D array
print("2D Array:")
print(two_d_array)

# Subset the first 5 elements from the second row (index 1)
subset = two_d_array[1, :5]

# Print the subset
print("Subset of the first 5 elements from the second row:")
print(subset)


2D Array:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
Subset of the first 5 elements from the second row:
[ 6  7  8  9 10]


<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>9. Write a program to find common values between two arrays 
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the lists given below:**<br>

    prices_monday = [10, 30, 50, 60, 90]

    prices_tuesday = [50, 20, 80, 125, 10, 70]

In [9]:
# type your code here
import numpy as np

# Given lists of prices
prices_monday = [10, 30, 50, 60, 90]
prices_tuesday = [50, 20, 80, 125, 10, 70]

# Convert the lists to NumPy arrays
monday_array = np.array(prices_monday)
tuesday_array = np.array(prices_tuesday)

# Find common values between the two arrays
common_values = np.intersect1d(monday_array, tuesday_array)

# Print the common values
print("Common values between the two arrays:")
print(common_values)


Common values between the two arrays:
[10 50]


<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>10. Write a program to find BMI of the patients whose height and weight is provided in the list given below 
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the lists given below:**<br>

    list of weights (in kg)
    weights = [57, 69, 54, 65 ,71, 62, 56]

    list of heights (in m)<br>
    heights = [1.59, 1.75, 1.66, 1.74, 1.64, 1.72, 1.53] 

In [10]:
# type your code here
# List of weights in kg
weights = [57, 69, 54, 65, 71, 62, 56]

# List of heights in meters
heights = [1.59, 1.75, 1.66, 1.74, 1.64, 1.72, 1.53]

# Function to calculate BMI
def calculate_bmi(weights, heights):
    bmi_list = []
    for weight, height in zip(weights, heights):
        bmi = weight / (height ** 2)
        bmi_list.append(bmi)
    return bmi_list

# Calculate and print the BMI for each patient
bmi_results = calculate_bmi(weights, heights)

for index, bmi in enumerate(bmi_results):
    print(f"Patient {index + 1}: BMI = {bmi:.2f}")


Patient 1: BMI = 22.55
Patient 2: BMI = 22.53
Patient 3: BMI = 19.60
Patient 4: BMI = 21.47
Patient 5: BMI = 26.40
Patient 6: BMI = 20.96
Patient 7: BMI = 23.92


<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>11. Write a program to add a new column ([5,7]) at the last position in the array given below 
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the array given below:**

    array1 = [[[3, 4], [8, 2],[5, 9]]]

In [13]:
import numpy as np

# Given array
array1 = np.array([[[3, 4], [8, 2], [5, 9]]])

# New column to be added
new_column = np.array([[5, 7]])

# Reshape the new column to match the existing array's structure
new_column_reshaped = new_column.reshape(1, 1, 2)

# Concatenate the new column at the last position
updated_array = np.concatenate((array1, new_column_reshaped), axis=1)

# Print the updated array
print("Updated Array:")
print(updated_array)


Updated Array:
[[[3 4]
  [8 2]
  [5 9]
  [5 7]]]


<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>12. Write a code to print the identity matrix of order 5</b>
                </font>
            </div>
        </td>
    </tr>
</table>

In [14]:
# type your code here
import numpy as np

# Create an identity matrix of order 5
identity_matrix = np.eye(5)

# Print the identity matrix
print("Identity Matrix of Order 5:")
print(identity_matrix)


Identity Matrix of Order 5:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>13. Write a program to transpose a matrix 
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the matrix given below:**
    
    M = [[15, 17, 45, 56], [7, 42, 15, 63], [54, 3, 61, 41], [0, 87, 16, 20]]

In [15]:
# type your code here
import numpy as np

# Given matrix
M = [[15, 17, 45, 56], 
     [7, 42, 15, 63], 
     [54, 3, 61, 41], 
     [0, 87, 16, 20]]

# Convert the matrix to a NumPy array
matrix = np.array(M)

# Transpose the matrix
transposed_matrix = matrix.T

# Print the transposed matrix
print("Transposed Matrix:")
print(transposed_matrix)


Transposed Matrix:
[[15  7 54  0]
 [17 42  3 87]
 [45 15 61 16]
 [56 63 41 20]]


<a id="Stacking"> </a>
## 3. Stacking

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>14. Write a program to combine the two arrays vertically</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the arrays given below: (or create your own array)**<br>

    A1 = [[5, 9], [7, 6]]

    A2 = [[8,-7], [0,4]]

Combine the array A2 with A1

In [16]:
# type your code here
import numpy as np

# Define the arrays
A1 = [[5, 9], [7, 6]]
A2 = [[8, -7], [0, 4]]

# Convert the lists to NumPy arrays
array1 = np.array(A1)
array2 = np.array(A2)

# Combine the arrays vertically
combined_array = np.vstack((array1, array2))

# Print the combined array
print("Combined Array:")
print(combined_array)


Combined Array:
[[ 5  9]
 [ 7  6]
 [ 8 -7]
 [ 0  4]]


<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>15. Write a code to combine the two arrays horizontally</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the arrays given below: (or create your own array)**

    A1 = [[-81, 75, 40], [27, 67, 52]]

    A2 = [[15, 54], [39, 56]]

Combine the array A2 with A1

In [17]:
# type your code here
import numpy as np

# Define the arrays
A1 = [[-81, 75, 40], [27, 67, 52]]
A2 = [[15, 54], [39, 56]]

# Convert the lists to NumPy arrays
array1 = np.array(A1)
array2 = np.array(A2)

# Combine the arrays horizontally
combined_array = np.hstack((array1, array2))

# Print the combined array
print("Combined Array:")
print(combined_array)


Combined Array:
[[-81  75  40  15  54]
 [ 27  67  52  39  56]]


<a id="Splitting"> </a>
## 4. Splitting

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>16. Write a code to divide the array into three sub-arrays containing
                       equal number of rows</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the array given below:**<br>

    A = [[4, 7], [2, -3], [8, 1], [0, 9], [5,-1], [8, 3]]

In [18]:
# type your code here
import numpy as np

# Define the array
A = [[4, 7], [2, -3], [8, 1], [0, 9], [5, -1], [8, 3]]

# Convert the list to a NumPy array
array = np.array(A)

# Calculate the number of rows for each sub-array
rows_per_subarray = array.shape[0] // 3

# Create sub-arrays
sub_array1 = array[:rows_per_subarray]
sub_array2 = array[rows_per_subarray:2*rows_per_subarray]
sub_array3 = array[2*rows_per_subarray:]

# Print the sub-arrays
print("Sub-array 1:")
print(sub_array1)

print("\nSub-array 2:")
print(sub_array2)

print("\nSub-array 3:")
print(sub_array3)


Sub-array 1:
[[ 4  7]
 [ 2 -3]]

Sub-array 2:
[[8 1]
 [0 9]]

Sub-array 3:
[[ 5 -1]
 [ 8  3]]


<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>17. Write a program to divide the array into two sub-arrays containing equal number of columns
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the array given below:**

    B = [[8, 7, 0, 9], [2, -3, 5, 10], [8, 5, -1,3]]

In [19]:
# type your code here
import numpy as np

# Define the array
B = [[8, 7, 0, 9], [2, -3, 5, 10], [8, 5, -1, 3]]

# Convert the list to a NumPy array
array = np.array(B)

# Calculate the number of columns for each sub-array
cols_per_subarray = array.shape[1] // 2

# Create sub-arrays
sub_array1 = array[:, :cols_per_subarray]
sub_array2 = array[:, cols_per_subarray:]

# Print the sub-arrays
print("Sub-array 1:")
print(sub_array1)

print("\nSub-array 2:")
print(sub_array2)


Sub-array 1:
[[ 8  7]
 [ 2 -3]
 [ 8  5]]

Sub-array 2:
[[ 0  9]
 [ 5 10]
 [-1  3]]


<a id="loop"> </a>
## 5. For Loop

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>18. Write a program to perform one-to-one mapping of the two lists</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the lists given below: (or create your own lists)**<br>

    L1 = [45, 67, 56, 71, 54, 62, 56]

    L2 = [21, 52, 64, 10, 49, 74, 26]

In [20]:
# type your code here
# Given lists
L1 = [45, 67, 56, 71, 54, 62, 56]
L2 = [21, 52, 64, 10, 49, 74, 26]

# Create a one-to-one mapping using a dictionary
one_to_one_mapping = dict(zip(L1, L2))

# Print the resulting mapping
print("One-to-One Mapping:")
print(one_to_one_mapping)


One-to-One Mapping:
{45: 21, 67: 52, 56: 26, 71: 10, 54: 49, 62: 74}


<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>19. Define a for loop to apply the function (2x-1)/(x+5) on every element of an array </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the list given below:**
    
    numbers = [6, 5, 3, 15]

In [21]:
# type your code here
# Given list
numbers = [6, 5, 3, 15]

# Define the function
def apply_function(x):
    return (2 * x - 1) / (x + 5)

# Apply the function using a for loop
results = []
for num in numbers:
    result = apply_function(num)
    results.append(result)

# Print the results
print("Results:")
print(results)


Results:
[1.0, 0.9, 0.625, 1.45]
